n_stacks: 1
n_skips: 1
max_n_frames: 1600
conv_in_channel: 1
conv_channels: '32_32'
conv_kernel_sizes: (3,3)_(3,3)
conv_strides: (1,1)_(1,1)
conv_poolings: (1,1)_(2,2)
subsample: '1_1_1_2_1_1_1_2_1_1_1_1'
subsample_type: max_pool
enc_type: conv_conformer
conformer_kernel_size: 15
conformer_normalization: layer_norm
enc_n_layers: 12
transformer_enc_pe_type: relative
transformer_enc_clamp_len: 10
transformer_enc_d_model: 256
transformer_enc_d_ff: 512
transformer_enc_n_heads: 8
dec_type: transformer_al
dec_n_layers: 6
transformer_dec_pe_type: 1dconv3L
transformer_dec_attn_type: scaled_dot
transformer_dec_d_model: 256
transformer_dec_d_ff: 512
transformer_dec_n_heads: 8
tie_embedding: false
ctc_fc_list: '512'
batch_size: 10000
batch_size_type: frame
n_epochs: 200
convert_to_sgd_epoch: 200
print_step: 6000
metric: edit_distance
optimizer: noam
lr_factor: 5.0
early_stop_patient_n_epochs: 5
shuffle_bucket: true
sort_stop_epoch: 100
eval_start_epoch: 1
warmup_n_steps: 25000
accum_grad_n_steps: 16
param_init: 0.1
clip_grad_norm: 5.0
dropout_in: 0.0
dropout_enc: 0.1
dropout_dec: 0.1
dropout_emb: 0.1
dropout_att: 0.0
weight_decay: 1.0e-06
lsm_prob: 0
ctc_weight: 0.8
ctc_lsm_prob: 0.1
mtl_per_batch: false
task_specific_layer: false
freq_width: 27
n_freq_masks: 2
time_width: 100
n_time_masks: 2
time_width_upper: 1.0
teacher_in: false
temperature: 1
contrastive: true
penalize_prediction: true
distillation_weight: 0.1
teacher: ''
n_gpus: 4
cudnn_benchmark: 1
cudnn_deterministic: 0
train_dtype: float32
resume: ''
job_name: false
stdout: 0
remove_old_checkpoints: true
use_wandb: 0
seed: 1
workers: 2
pin_memory: 0
local_rank: 0
local_world_size: 4
dist_backend: nccl
eval_sets: []
nlsyms: false
corpus: librispeech
dict: /home/ubuntu/newwork/AL-NAT-server/librispeech/dict.txt
unit: wp
wp_model: /home/ubuntu/newwork/AL-NAT-server/librispeech/wp.model
lr: 0.001
eps: 1.0e-06
lr_decay_type: always
lr_decay_start_epoch: 10
lr_decay_rate: 0.9
lr_decay_patient_n_epochs: 0
warmup_start_lr: 0
recog_stdout: false
recog_n_gpus: 0
recog_sets: []
recog_model: false
recog_dir: false
recog_batch_size: 1
recog_n_average: 1
config2: null
train_set_sub1: false
train_set_sub2: false
train_word_alignment: null
train_ctc_alignment: null
dev_set_sub1: false
dev_set_sub2: false
dev_word_alignment: null
dev_ctc_alignment: null
dict_sub1: false
dict_sub2: false
unit_sub1: false
unit_sub2: false
wp_model_sub1: false
wp_model_sub2: false
input_type: speech
n_splices: 1
min_n_frames: 40
dynamic_batching: true
input_noise_std: 0
weight_noise_std: 0
sequence_summary_network: false
enc_n_layers_sub1: 0
enc_n_layers_sub2: 0
enc_grad_no: false
dec_type_sub1: lstm
dec_type_sub2: lstm
dec_config_sub1: null
dec_config_sub2: null
sort_short2long: true
sort_by: input
asr_init: ''
asr_init_enc_only: false
freeze_encoder: false
adaptive_number_ratio: 0.0
adaptive_size_ratio: 0.0
max_n_time_masks: 20
teacher_input: 0
chunk_al: 0
stride_al: 5
kernel_al: 8
nbest_bac: 3
gamma: 0.75
alpha: 0.5
do_bac: false
do_normal: false
total_weight: 1.0
ctc_weight_sub1: 0.0
ctc_weight_sub2: 0.0
sub1_weight: 0.0
sub2_weight: 0.0
bwd_weight: 0.0
external_lm: null
lm_fusion: ''
lm_init: false
discourse_aware: false
mbr_training: false
mbr_ce_weight: 0.0
mbr_nbest: 4
mbr_softmax_smoothing: 0.8
bptt: 0
mem_len: 0
teacher_lm: false
replace_sos: false
recog_word_alignments: []
recog_first_n_utt: -1
recog_model_bwd: false
recog_unit: false
recog_metric: edit_distance
recog_oracle: false
recog_beam_width: 28
recog_alpha: 0.5
recog_beta: 2
recog_max_len_ratio: 1.0
recog_min_len_ratio: 0.0
recog_length_penalty: 0.0
recog_length_norm: false
recog_coverage_penalty: 0.0
recog_coverage_threshold: 0.0
recog_gnmt_decoding: false
recog_eos_threshold: 1.5
recog_lm_weight: 0.0
recog_ilm_weight: 0.0
recog_lm_second_weight: 0.0
recog_lm_bwd_weight: 0.0
recog_cache_embedding: true
recog_ctc_weight: 0.0
recog_lm: false
recog_lm_second: false
recog_lm_bwd: false
recog_resolving_unk: false
recog_fwd_bwd_attention: false
recog_bwd_attention: false
recog_reverse_lm_rescoring: false
recog_asr_state_carry_over: false
recog_lm_state_carry_over: false
recog_softmax_smoothing: 1.0
recog_wordlm: false
recog_longform_max_n_frames: 0
recog_streaming: false
recog_streaming_encoding: false
recog_block_sync: false
recog_block_sync_size: 40
recog_ctc_spike_forced_decoding: false
recog_ctc_vad: true
recog_ctc_vad_blank_threshold: 40
recog_ctc_vad_spike_threshold: 0.1
recog_ctc_vad_n_accum_frames: 4000
recog_mma_delay_threshold: -1
recog_mem_len: 0
recog_rnnt_beam_search_type: time_sync_mono
conv_normalization: ''
conv_bottleneck_dim: 0
transformer_ffn_bottleneck_dim: 0
transformer_layer_norm_eps: 1.0e-12
transformer_ffn_activation: swish
transformer_param_init: xavier_uniform
dropout_enc_layer: 0.0
transformer_enc_lookaheads: '0_0_0_0_0_0_0_0_0_0_0_0'
lc_chunk_size_left: '0'
lc_chunk_size_current: '0'
lc_chunk_size_right: '0'
lc_type: reshape
dropout_dec_layer: 0.0
dropout_head: 0.0
mocha_n_heads_mono: 1
mocha_n_heads_chunk: 1
mocha_chunk_size: 1
mocha_init_r: -4
mocha_eps: 1.0e-06
mocha_std: 1.0
mocha_no_denominator: false
mocha_1dconv: false
mocha_quantity_loss_weight: 0.0
mocha_latency_metric: ''
mocha_latency_loss_weight: 0.0
mocha_first_layer: 1
mocha_head_divergence_loss_weight: 0.0
share_chunkwise_attention: false
distributed: true
subsample_factor: 8
subsample_factor_sub1: 1
subsample_factor_sub2: 1
vocab: 9950
vocab_sub1: -1
vocab_sub2: -1
input_dim: 80
save_path: ''
use_apex: false
wandb_id: null
kenlm_path: /home/ubuntu/newwork/AL-NAT-server/librispeech/3-gram.klm